"""create phase d persistence tables

Revision ID: 549733be0747
Revises:
Create Date: 2026-09-05 02:05:54.390367
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '549733be0747'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sourcing_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_make', sa.String(length=100), nullable=False),
    sa.Column('vehicle_model', sa.String(length=100), nullable=False),
    sa.Column('vehicle_year', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=200), nullable=False),
    sa.Column('requested_reference', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('max_budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('selected_quote_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone_e164', sa.String(length=16), nullable=False),
    sa.Column('authorized_for_calls', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_e164')
    )
    op.create_table('webhook_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_event_id', sa.String(length=150), nullable=False),
    sa.Column('provider_call_id', sa.String(length=100), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_provider_event')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sourcing_request_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('safe_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sourcing_request_id'], ['sourcing_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_sourcing_request_id'), 'audit_events', ['sourcing_request_id'], unique=False)
    op.create_table('call_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sourcing_request_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('call_type', sa.String(length=20), nullable=False),
    sa.Column('logical_idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('provider_call_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("call_type IN ('quote', 'reservation')", name='ck_call_type'),
    sa.ForeignKeyConstraint(['sourcing_request_id'], ['sourcing_requests.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_idempotency_key', 'attempt_number', name='uq_call_logical_attempt')
    )
    op.create_table('sourcing_request_suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sourcing_request_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sourcing_request_id'], ['sourcing_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sourcing_request_id', 'supplier_id', name='uq_request_supplier')
    )
    op.create_index(op.f('ix_sourcing_request_suppliers_sourcing_request_id'), 'sourcing_request_suppliers', ['sourcing_request_id'], unique=False)
    op.create_index(op.f('ix_sourcing_request_suppliers_supplier_id'), 'sourcing_request_suppliers', ['supplier_id'], unique=False)
    op.create_table('supplier_quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sourcing_request_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('exact_reference_confirmed', sa.String(length=10), nullable=False),
    sa.Column('offered_reference', sa.String(length=200), nullable=True),
    sa.Column('in_stock', sa.String(length=10), nullable=False),
    sa.Column('manufacturer_or_brand', sa.String(length=200), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('tax_included', sa.String(length=10), nullable=False),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('pickup_available_today', sa.String(length=10), nullable=False),
    sa.Column('delivery_eta', sa.String(length=100), nullable=True),
    sa.Column('quote_valid_until', sa.String(length=100), nullable=True),
    sa.Column('supplier_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sourcing_request_id'], ['sourcing_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_quotes_sourcing_request_id'), 'supplier_quotes', ['sourcing_request_id'], unique=False)
    op.create_index(op.f('ix_supplier_quotes_supplier_id'), 'supplier_quotes', ['supplier_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sourcing_request_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_quote_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_call_id', sa.String(length=100), nullable=True),
    sa.Column('reservation_reference', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending_approval','calling','confirmed','refused','unavailable','unclear','no_answer','failed')", name='ck_reservation_status'),
    sa.ForeignKeyConstraint(['sourcing_request_id'], ['sourcing_requests.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['supplier_quote_id'], ['supplier_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sourcing_request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_index(op.f('ix_supplier_quotes_supplier_id'), table_name='supplier_quotes')
    op.drop_index(op.f('ix_supplier_quotes_sourcing_request_id'), table_name='supplier_quotes')
    op.drop_table('supplier_quotes')
    op.drop_index(op.f('ix_sourcing_request_suppliers_supplier_id'), table_name='sourcing_request_suppliers')
    op.drop_index(op.f('ix_sourcing_request_suppliers_sourcing_request_id'), table_name='sourcing_request_suppliers')
    op.drop_table('sourcing_request_suppliers')
    op.drop_table('call_attempts')
    op.drop_index(op.f('ix_audit_events_sourcing_request_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('webhook_receipts')
    op.drop_table('suppliers')
    op.drop_table('sourcing_requests')
    # ### end Alembic commands ###
